name: Pytest & flake8 control Push
on: push

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout on master
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest

      # Step 5: Check PEP8 compliance
      - name: Lint code with flake8
        run: |
          flake8 .
